// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  get profile() {
    return __t.option(Profile);
  },
  get entries() {
    return __t.array(EntryView);
  },
});
export type Account = __Infer<typeof Account>;

export const Entry = __t.object("Entry", {
  id: __t.u64(),
  key: __t.string(),
  identity: __t.identity(),
  slug: __t.string(),
  entryType: __t.string(),
  teamName: __t.string(),
  teammates: __t.array(__t.string()),
  extraKeys: __t.array(__t.string()),
  extraValues: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Entry = __Infer<typeof Entry>;

export const EntryView = __t.object("EntryView", {
  slug: __t.string(),
  entryType: __t.string(),
  teamName: __t.string(),
  teammates: __t.array(__t.string()),
  extraKeys: __t.array(__t.string()),
  extraValues: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type EntryView = __Infer<typeof EntryView>;

export const LinkCode = __t.object("LinkCode", {
  code: __t.string(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type LinkCode = __Infer<typeof LinkCode>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  memberNo: __t.u64(),
  email: __t.string(),
  name: __t.string(),
  institution: __t.string(),
  year: __t.string(),
  country: __t.string(),
  chapter: __t.string(),
  discord: __t.string(),
  interests: __t.string(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Member = __Infer<typeof Member>;

export const Profile = __t.object("Profile", {
  memberNo: __t.u64(),
  name: __t.string(),
  email: __t.string(),
  institution: __t.string(),
  year: __t.string(),
  country: __t.string(),
  chapter: __t.string(),
  discord: __t.string(),
  interests: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

export const Tally = __t.object("Tally", {
  slug: __t.string(),
  entries: __t.u64(),
  people: __t.u64(),
});
export type Tally = __Infer<typeof Tally>;

export const Window = __t.object("Window", {
  slug: __t.string(),
  opensAt: __t.timestamp(),
  closesAt: __t.timestamp(),
  endsAt: __t.timestamp(),
});
export type Window = __Infer<typeof Window>;

