// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as IssueLinkCodeProcedure from "../issue_link_code_procedure";
import * as MyAccountProcedure from "../my_account_procedure";
import * as RedeemLinkCodeProcedure from "../redeem_link_code_procedure";

export type IssueLinkCodeArgs = __Infer<typeof IssueLinkCodeProcedure.params>;
export type IssueLinkCodeResult = __Infer<typeof IssueLinkCodeProcedure.returnType>;
export type MyAccountArgs = __Infer<typeof MyAccountProcedure.params>;
export type MyAccountResult = __Infer<typeof MyAccountProcedure.returnType>;
export type RedeemLinkCodeArgs = __Infer<typeof RedeemLinkCodeProcedure.params>;
export type RedeemLinkCodeResult = __Infer<typeof RedeemLinkCodeProcedure.returnType>;

