// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import EnrollReducer from "../enroll_reducer";
import ForgetMeReducer from "../forget_me_reducer";
import SaveMemberReducer from "../save_member_reducer";
import WithdrawReducer from "../withdraw_reducer";

export type EnrollParams = __Infer<typeof EnrollReducer>;
export type ForgetMeParams = __Infer<typeof ForgetMeReducer>;
export type SaveMemberParams = __Infer<typeof SaveMemberReducer>;
export type WithdrawParams = __Infer<typeof WithdrawReducer>;

